added delete and rename functions

diff --git a/bin/resume b/bin/resume
--- a/bin/resume
+++ b/bin/resume
@@ -92,6 +92,7 @@ commands:
  new                 create or edit a resume (or cover letter)
  import              import an external document
  delete              remove a resume (from the working space)
+ rename              rename a resume
  publish             publish resume to ${_defaultPublishURL}
  list                browse documents
  inspect             run tig on the repo
@@ -118,9 +119,9 @@ _getOpts () {
 	local OPTIND
 	# make the original environment available to _shell for calling back into main
 	export _originalParameters=${*}
-	_debug "${FUNCNAME}: positional parameters read: $*"
+	_debug "${FUNCNAME[0]}: positional parameters read: $*"
 	while getopts ":hsdlva:w:" flag ; do
-		_debug "${FUNCNAME}: OPTIND=$OPTIND flag=$flag"
+		_debug "${FUNCNAME[0]}: OPTIND=$OPTIND flag=$flag"
 		case ${flag} in 
 			h)
 				_printInfo ; _printUsage; _printCommands; exit 0
@@ -138,15 +139,15 @@ _getOpts () {
         ;;
 
  	    s)
-				_debug "${FUNCNAME}: enabling silent mode with flag -$flag"
+				_debug "${FUNCNAME[0]}: enabling silent mode with flag -$flag"
  	      export _SILENT=true
 				;;
 			d)
-				_debug "${FUNCNAME}: enabled debug mode with flag -$flag"
+				_debug "${FUNCNAME[0]}: enabled debug mode with flag -$flag"
 				export _DEBUG=true
 				;;
 			l)
-				_debug "${FUNCNAME}: enabled log mode with flag -$flag"
+				_debug "${FUNCNAME[0]}: enabled log mode with flag -$flag"
 				export _LOG=true
 				;;
 			v)
@@ -161,37 +162,45 @@ _getOpts () {
 	# export a paired down parameter string flags and args read within this
 	# function will be discarded, leaving behind only that which the rest needs
 	export _workingParams=$*
-	_debug "${FUNCNAME}: _LOG=${_LOG}"
-	_debug "${FUNCNAME}: _SILENT=${_SILENT}"
-	_debug "${FUNCNAME}: _DEBUG=${_DEBUG}"
+	_debug "${FUNCNAME[0]}: _LOG=${_LOG}"
+	_debug "${FUNCNAME[0]}: _SILENT=${_SILENT}"
+	_debug "${FUNCNAME[0]}: _DEBUG=${_DEBUG}"
 	return
 }
 
 _getSubcommand() {
 	# look for the first subcommand and set _subCommand accordingly
 	while ((${#})); do
-		_debug "${FUNCNAME}: reading parameter '${1}'"
+		_debug "${FUNCNAME[0]}: reading parameter '${1}'"
 		case $1 in
 			help)
 				_printInfo ; _printUsage; exit 0
 				;;
 			new)
-				_debug "${FUNCNAME}: '$1' called, checking for $1 flags now"
+				_debug "${FUNCNAME[0]}: '$1' called, checking for $1 flags now"
 				_subCommand=$1
 				_getAddOpts
 				return
 				;;
 			import)
-				_debug "${FUNCNAME}: '$1' called, checking for $1 flags"
+				_debug "${FUNCNAME[0]}: '$1' called, checking for $1 flags"
 				_subCommand=$1
 				return
 				;;
 			list)
-				_debug "${FUNCNAME}: '$1' called"
+				_debug "${FUNCNAME[0]}: '$1' called"
 				_subCommand=$1
 				return
 				;;
 			publish)
+				_subCommand=$1
+				return
+				;;
+			delete)
+				_subCommand=$1
+				return
+				;;
+			rename)
 				_subCommand=$1
 				return
 				;;
@@ -220,9 +229,9 @@ _setEnv() {
 	# set (and print) the environment
 	#_info "setting up environment now"
 	# get the name etc
-	self=$(basename $0)
+	self=$(basename "$0")
 	self_call="$0"
-	self_absolute=$(readlink -f $0)
+	self_absolute=$(readlink -f "$0")
 	self_pwd=$(pwd)
 	export _studioDir="$(dirname ~/.)/${_studioDirName}"
 	export _resumeDir="${_studioDir}/${_resumeDirName}"
@@ -262,10 +271,10 @@ _isEnvSufficient() {
 	local _sufficient=true
 	for _required in "${_requiredCommands[@]}"; do
 		if ! hash "${_required}" 2>/dev/null; then
-			_warn "${FUNCNAME}: ${_required} not found"
+			_warn "${FUNCNAME[0]}: ${_required} not found"
 			_sufficient=false
 		else
-			_debug "${FUNCNAME}: ${_required} found"
+			_debug "${FUNCNAME[0]}: ${_required} found"
 		fi
 	done
 	[ ${_sufficient} = true ] && return 0 || return 1
@@ -319,7 +328,7 @@ _getAddOpts() {
 	# check for _add() flags and args
 	local OPTIND=1
 	set -- ${_workingParams}
-	_debug "${FUNCNAME}: positional parameters read: $*"
+	_debug "${FUNCNAME[0]}: positional parameters read: $*"
 	shift
 	while getopts ":d:" flag "$@"; do
 		case ${flag} in
@@ -329,7 +338,7 @@ _getAddOpts() {
 				_altDate="${OPTARG}"
 				;;
 			?)
-				 _error "${FUNCNAME}: unknown flag -$OPTARG"; exit 1
+				 _error "${FUNCNAME[0]}: unknown flag -$OPTARG"; exit 1
 				;;
 		esac
 	done
@@ -495,7 +504,7 @@ _new() {
 }
 
 _gitCommit() {
-	# relies on _path, _name, _state
+	# relies on _name, _state
   local _pathspec="${_state}/${_name}"
   git -C "${_resumeDir}" --git-dir="${_resumeGitDisk}" add "${_pathspec}"
   [[ $? != 0 ]] && { _warn "git add ${_pathspec} failed"; return 1; }
@@ -503,6 +512,42 @@ _gitCommit() {
   [[ $? != 0 ]] && { _warn "git commit failed"; return 1; }
 	return 0
 }
+
+_gitAdd() {
+	# relies on _name, _state
+  local _pathspec="${_state}/${_name}"
+  git -C "${_resumeDir}" --git-dir="${_resumeGitDisk}" add "${_pathspec}"
+  [[ $? != 0 ]] && { _warn "git add ${_pathspec} failed"; return 1; }
+  git -C "${_resumeDir}" --git-dir="${_resumeGitDisk}" commit -q -m "saved ${_name} as ${_state}"
+  [[ $? != 0 ]] && { _warn "git commit failed"; return 1; }
+	return 0
+}
+
+_gitDelete() {
+	# relies on _name, _state
+  local _pathspec="${_state}/${_name}"
+	rm "${_resumeDir}/${_state}/${_name}"
+  [[ $? != 0 ]] && { _warn "deletion of ${_name} failed"; return 1; }
+  git -C "${_resumeDir}" --git-dir="${_resumeGitDisk}" rm --quiet "${_pathspec}" 
+  [[ $? != 0 ]] && { _warn "git rm of ${_pathspec} failed"; return 1; }
+  git -C "${_resumeDir}" --git-dir="${_resumeGitDisk}" commit -q -m "deleted ${_name} from ${_state}"
+  [[ $? != 0 ]] && { _warn "git commit failed"; return 1; }
+	return 0
+}
+
+_gitRename() {
+	# relies on _oldName, _newName, _state
+  local _oldPathspec="${_state}/${_oldName}"
+  local _newPathspec="${_state}/${_newName}"
+	#mv "${_resumeDir}/${_state}/${_oldName}" "${_resumeDir}/${_state}/${_newName}"
+  #[[ $? != 0 ]] && { _warn "mv of '${_oldName}' to '${_newName}' failed"; return 1; }
+  git -C "${_resumeDir}" --git-dir="${_resumeGitDisk}" mv "${_oldPathspec}" "${_newPathspec}"
+  [[ $? != 0 ]] && { _warn "git mv of ${_oldPathspec} to ${_newPathspec} failed"; return 1; }
+  git -C "${_resumeDir}" --git-dir="${_resumeGitDisk}" commit -q -m "renamed ${_oldName} to ${_newName}"
+  [[ $? != 0 ]] && { _warn "git commit failed"; return 1; }
+	return 0
+}
+
 
 _checkChanges() {
 	# determine the operation and check if changes were made
@@ -555,7 +600,7 @@ _picker() {
 	local _query			# the query string used in fzf
 	local _selection	# the selected string
 	local _name				# the name returned
-	export _guide="${1:-'select a name'}"
+	export _guide="${1:-select a name}"
 	# maintain state
 	export _tmp="/tmp/studio.picker"
 	[[ -d ${_tmp} ]] || mkdir ${_tmp}
@@ -655,7 +700,7 @@ _seedFile() {
 	# and a name for the new ($2)
 	# seed the new file with the source
 	# return 0 if success, 1 if failed
-	_info "seeding from ${1}"
+	_debug "seeding from ${1}"
 	[[ -e "${2}" ]] && { _warn "'${2}' exists, cannot clobber"; return 1; }
 	cat "${1}" > "${2}"
 	[[ $? = 0 ]] && return
@@ -737,12 +782,12 @@ _import() {
 	local _state
 	_importedFile=$(_finder)
 	[[ -f "${_importedFile}" ]] || { _warn "'${_importedFile}' is not a file"; return; } 
-	_info "imported file is ${_importedFile}"
+	_debug "imported file is ${_importedFile}"
 	_name=$(_picker "choose a new name")
 	_doesKeyExist "${_name}" && { _warn "'${_name}' already exists, new name required"; return; }
 	[[ -d "${_name}" ]] && { _warn "'${_name}' is a directory silly, no can do"; return; }
 	[[ -z "${_name}" ]] && { _warn "'${_name}' is empty...not allowed"; return; }
-	_info "name chosen is ${_name}"
+	_debug "name chosen is ${_name}"
 	export _path="${_resumeDir}/intent/${_name}"
   _seedFile "${_importedFile}" "${_path}"
 	_edit
@@ -973,6 +1018,47 @@ _publish () {
 	[[ $? == 0 ]] && _info "success" || _warn "failed to upload"
 }
 
+
+############################
+# DELETE
+############################
+
+_delete() {
+	local _nameToDelete
+	local _state
+	local _path
+	_nameToDelete=$(_picker "choose what to delete")
+	_doesKeyExist "${_nameToDelete}" || { _warn "'${_nameToDelete}' does not exist"; return; }
+  read -rsn1 -p "$(_ask "press ${boldred}d${reset} to confirm deletion of '${_nameToDelete}'")" _confirm
+	echo
+	[[ ${_confirm} = "d" ]] || { _warn "aborted delete of '${_nameToDelete}'"; return; }
+	export _name=${_nameToDelete}
+	export _state=$(_getKeyState "${_nameToDelete}")
+	_gitDelete || _error "_gitDelete for ${_name} failed"
+}
+
+############################
+# RENAME
+############################
+
+_rename() {
+	local _oldName
+	local _newName
+	local _state
+	local _commonPath
+	_oldName=$(_picker "choose name to rename")
+	_doesKeyExist "${_oldName}" || { _warn "'${_oldName}' does not exist"; return; }
+	_newName=$(_picker "choose new name")
+	_doesKeyExist "${_newName}" && { _warn "'${_newName}' is not unique"; return; }
+  read -rsn1 -p "$(_ask "press ${boldred}y${reset} to rename '${_oldName}' to '${_newName}'")" _confirm
+	echo
+	[[ ${_confirm} = "y" ]] || { _warn "aborted rename of '${_oldName}'"; return; }
+	export _oldName
+	export _newName
+	export _state=$(_getKeyState "${_oldName}")
+	_gitRename || _error "_gitRename for ${_oldName} failed"
+}
+
 ############################
 # CREATE
 ############################
@@ -1138,10 +1224,7 @@ HEREDOC
 		elif [[ "${__input}" =~ (^help$|^h$|^\?$) ]]; then
 			_printShellUsage
 		elif [[ "${__input}" =~ (^list$|^l$) ]]; then
-			_picker || true
-		# testing new finder
-		elif [[ "${__input}" =~ (^f$) ]]; then
-			_finder
+			_picker "browsing only" || true
 		elif [[ "${__input}" =~ (^import$) ]]; then
 			_import
 		elif [[ "${__input}" =~ (^pub$) ]]; then
@@ -1178,11 +1261,11 @@ HEREDOC
 main() {
 	# what are we trying to do (read all the positional parameters and set VARS)
 	_getOpts "${@}"
-	_debug "${FUNCNAME}: parameters read: ${*}"
-	_debug "${FUNCNAME}: paired-down parameters: $_workingParams"
+	_debug "${FUNCNAME[0]}: parameters read: ${*}"
+	_debug "${FUNCNAME[0]}: paired-down parameters: $_workingParams"
 	_getSubcommand $_workingParams
-	_debug "${FUNCNAME}: _subCommand: ${_subCommand:-}"
-	_debug "${FUNCNAME}: remaining args: $_workingParams"
+	_debug "${FUNCNAME[0]}: _subCommand: ${_subCommand:-}"
+	_debug "${FUNCNAME[0]}: remaining args: $_workingParams"
 	# setup the environment after processing all command line parameters
 	_setEnv
 	# reinitialize log functions after processing all command line options
@@ -1211,4 +1294,10 @@ main() {
 	_debug "now calling the eval to run '${_subCommand:-}'"
 	[ -n "${_subCommand:-}" ] && eval _"${_subCommand}" || exit
 }
-main "${@}"
+# don't run if sourced
+if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
+	main "${@}"
+	if [ $? -gt 0 ]; then
+		exit 1
+	fi
+fi
